INSERT INTO categories (category_name) VALUES
                                           ('소설'),
                                           ('자기계발'),
                                           ('경제/경영'),
                                           ('역사'),
                                           ('과학'),
                                           ('철학'),
                                           ('심리학'),
                                           ('예술'),
                                           ('문학'),
                                           ('정치'),
                                           ('사회'),
                                           ('종교'),
                                           ('여행'),
                                           ('요리'),
                                           ('건강'),
                                           ('스포츠'),
                                           ('취미'),
                                           ('만화'),
                                           ('에세이'),
                                           ('교육'),
                                           ('어린이'),
                                           ('청소년'),
                                           ('외국어'),
                                           ('IT/컴퓨터'),
                                           ('프로그래밍'),
                                           ('디자인'),
                                           ('사진'),
                                           ('패션'),
                                           ('건축'),
                                           ('음악'),
                                           ('영화'),
                                           ('드라마'),
                                           ('시/에세이'),
                                           ('잡지'),
                                           ('전기/자서전'),
                                           ('학습서'),
                                           ('토익/토플'),
                                           ('자격증'),
                                           ('수험서'),
                                           ('공학'),
                                           ('자연'),
                                           ('농업'),
                                           ('환경'),
                                           ('의학'),
                                           ('간호'),
                                           ('치의학'),
                                           ('한의학'),
                                           ('문헌정보학'),
                                           ('법학'),
                                           ('수학'),
                                           ('물리학');


INSERT INTO Products (
    product_name, publisher_name, author_name, translator_name,
    purchase_price, unit_price, discount_price, selling_price,
    description, thumbnail_image_data, product_image_data,
    product_status, category_id
)
VALUES
    ('Spring Boot Mastery', 'TechBooks Publishing', 'John Doe', NULL,
     25000, 30000, 5000, 25000,
     'Comprehensive guide to mastering Spring Boot.',
     'https://example.com/thumbnail1.jpg', 'https://example.com/product1.jpg',
     'ACTIVE', 1),

    ('React Essentials', 'Frontend Focus', 'Jane Smith', NULL,
     22000, 28000, 6000, 22000,
     'An essential book for React beginners and professionals.',
     'https://example.com/thumbnail2.jpg', 'https://example.com/product2.jpg',
     'ACTIVE', 2),

    ('Java Deep Dive', 'Coding Insight', 'Alice Johnson', 'Michael Brown',
     30000, 35000, 5000, 30000,
     'Deep dive into Java for advanced developers.',
     'https://example.com/thumbnail3.jpg', 'https://example.com/product3.jpg',
     'INACTIVE', 3),

    ('Python Data Science', 'Data Books Co.', 'Robert White', NULL,
     28000, 33000, 5000, 28000,
     'Practical approaches to data science with Python.',
     'https://example.com/thumbnail4.jpg', 'https://example.com/product4.jpg',
     'ACTIVE', 4),

    ('Effective Communication', 'Soft Skills Press', 'Emma Green', 'Chris Black',
     18000, 25000, 7000, 18000,
     'Learn to communicate effectively in the workplace.',
     'https://example.com/thumbnail5.jpg', 'https://example.com/product5.jpg',
     'ACTIVE', 5);
